debezium/debezium.github.io

- docs/connectors/mysql.asciidoc
GTIDs are available in MySQL 5.6.5, so made it a bit more clear that GTIDs cannot be used with earlier versions of MySQL.
> DBZ-82 Updated documentation to be a bit more clear

- docs/tutorial.asciidoc
Just a minor change where it was written 0.4 instead of 0.5 as 0.5 is the latest.
> Updated tutorial.asciidoc

- docs/connectors/mongodb.asciidoc
also add several examples showing how different _id field types will get encoded as JSON strings
> DBZ-306 update docs to reflect changes in event key’s payload

- docs/configuration/avro.asciidoc
Our image defines its [own environment variables](https://github.com/debezium/docker-images/blob/master/connect-base/0.6/docker-entrypoint.sh#L23-L26), overriding the existing `CONNECT_...` ones.
I'm not sure whether that's really a good idea, but as we started with it, we should also do it for the two registry URL ones which currently need to be given via the original variables. I'll send a PR for the images repo for that.
> Fixing incorrect variable names in Avro instructions

- docs/openshift.asciidoc
The website should not be using files from the master branch, which might be changing. It should use the release instead. This PR changes the links to the files from the 0.1.0 release.
> Use Strimzi 0.1.0  instead of master

- docs/embedded.asciidoc
https://issues.jboss.org/browse/DBZ-537
For the sake of fromatting I created a convention in the table that package names are replaced with `<...>` string. Otherwise the table would overflow or we we would need to fill class names with `ZWSP` to enable breaking them in the text flow.
> DBZ-537 Document engine properties

- docs/connectors/mysql.asciidoc
Updated documentation for issue DBZ-602 (https://github.com/debezium/debezium/pull/456)
New configuration entry for snapshot.locking.mode:
Deprecation notice for snapshot.mininal.locks:
> [DBZ-602] - update documentation

- _config/site.yml
- docs/openshift.asciidoc
https://issues.jboss.org/browse/DBZ-654
> DBZ-654 Instructions for Strimzi 0.2.0

- docs/connectors/mongodb.asciidoc
- docs/connectors/mysql.asciidoc
- docs/connectors/oracle.asciidoc
- docs/connectors/postgresql.asciidoc
https://issues.jboss.org/browse/DBZ-752
> DBZ-752 Table of contents for connector docs

- docs/connectors/postgresql.asciidoc
Documentation for PostgreSQL connector configuration updates from https://issues.jboss.org/browse/DBZ-911.
> Add documentation for schema.refresh.mode option

- docs/configuration/mongodb-event-flattening.asciidoc
As in https://github.com/debezium/debezium/pull/672
Both documentation were wrong pointing to a value `struct` when it should've been `document`
> DBZ-925 Change `array.encoding` to correct options

- docs/faq.asciidoc
Addresses a few typos found on the FAQ documentation
> Fixes typos in the FAQ documentation

- docs/tutorial.asciidoc
Apparently you need to escape the double quotes in the json body of the request on Windows.
> Update tutorial.asciidoc to note curl discrepancy on Windows

- docs/connectors/mongodb.asciidoc
- docs/connectors/oracle.asciidoc
- docs/connectors/postgresql.asciidoc
- docs/connectors/sqlserver.asciidoc
The property is now exposed in all connectors. Previously it was
available only for MySQL.
> DBZ-966 Describe snapshot.delay.ms property

- docs/faq.asciidoc
In the FAQ, under the `How to change the offsets of the source database` section, the `kafkacat` command is missing the `f` flag character preceding the format string (it only contains `-` instead of `-f`).
> Add missing `-f` flag to `kafkacat` cmd in the FAQ

- docs/embedded.asciidoc
This adds the docs for the `ChangeConsumer` to the EmbeddedEngine docs.
> DBZ-1080 Document new EmbeddedEngine API

- docs/connectors/postgresql.asciidoc
Gentle notation about delete events. All other events working with replica identity levels as expected (and as described in docs)
> DBZ-1029 note about postgres replica identity and 'delete' events

- docs/connectors/sqlserver.asciidoc
Removed snapshot.locking.mode and added snapshot.isolation.mode to SQL Server Connector documentation
> Updated docs to use snapshot.isolation.mode

- docs/connectors/sqlserver.asciidoc
The connector will not return warning message when the user doesn't have access to the cdc table, so it's better to verify it.
> Add documentation to verify if the user have access to cdc table

- blog/2019-05-23-tutorial-using-debezium-connectors-with-apache-pulsar.adoc
There is an issue with the link for pulsar images in the "Step 2: Start standalone Pulsar service" of [this blog](https://debezium.io/blog/2019/05/23/tutorial-using-debezium-connectors-with-apache-pulsar/). 
This was caused by a new release of pulsar between written and post this blog, and we leak a change for it. sorry for this.
> Fix link of pulsar binary download in blog post 2019-5-23

- docs/connectors/postgresql.asciidoc
This adds the docs for the custom snapshot modes including details on
the SPI snapshotter interface.
> Add documentation for PG custom snapshot modes

- docs/connectors/postgresql.asciidoc
@jpechane, minor doc fix which I noticed while PR reviewing.
> Postgres connector docs fix on TIMESTAMP mapping

- _config/site.yml
- docs/openshift.asciidoc
The OpenShift tutorial is currently using Strimzi 0.9.0. This PR updates it to the latest version - 0.13.0. It also changes how the Kafka and Kafka Connect are deployed from the templates (the `oc new-app` does not work on OCP4 because it deploys a custom resource) - the process works also with 3.11. 
Additionally it removed the mentiones of OpenShift Online and Dedicated where Strimzi doesn't work for quite a long time due to the limitations of these environments (not possible to install CRDs and Cluster Roles etc.)
> Update to Strimzi 0.13.0

- documentation/online-resources.asciidoc
I used Debezium in my example scenario in my recent Kafka Summit presentation. @gunnarmorling asked if I would open a PR to add a link to my slides.
> Adding a link to my recent Kafka Summit presentation slides

- _antora/supplemental_ui/css/debezium-antora.css
- _antora/supplemental_ui/layouts/default.hbs
- _antora/supplemental_ui/partials/head-styles.hbs
This renders documentation pages with a TOC section in a right navigational bar that is responsive based on the screen size.  On tablet and mobile devices, the TOC continues to be rendered at the top of the asciidoc page like it always has.
> Added support for right navbar for TOC on large screens

- CONTRIBUTING.md
- Rakefile
- playbook_author.yml
https://issues.jboss.org/browse/DBZ-1466
In order to use author mode, two things will be necessary:
1. Start docker mapping a local checked out copy of the Debezium main code repository as a volume using the name `/debezium`, e.g. `-v <local_path>:/debezium`
2. When running rake, also provide it with the `author` task, e.g. `rake clean author preview`.
> DBZ-1466 Add author mode support for locally building

- blog/2018-08-30-streaming-mysql-data-changes-into-kinesis.adoc
- blog/2018-09-20-materializing-aggregate-views-with-hibernate-and-debezium.adoc
- blog/2018-12-05-automating-cache-invalidation-with-change-data-capture.adoc
- blog/2018-12-19-debezium-0-9-0-beta2-released.adoc
- blog/2019-02-05-debezium-0-9-0-final-released.adoc
- blog/2019-02-13-debezium-0-9-1-final-released.adoc
- blog/2019-02-19-reliable-microservices-data-exchange-with-the-outbox-pattern.adoc
- blog/2019-03-14-debezium-meets-quarkus.adoc
- blog/2019-05-23-tutorial-using-debezium-connectors-with-apache-pulsar.adoc
- blog/2019-07-08-tutorial-sentry-debezium-container-images.adoc
- blog/2019-07-12-streaming-cassandra-at-wepay-part-1.adoc
- blog/2019-10-01-audit-logs-with-change-data-capture-and-stream-processing.adoc
- blog/2019-10-08-handling-unchanged-postgres-toast-values.adoc
- blog/2019-10-22-audit-logs-with-kogito.adoc
- stylesheets/debezium.less
Hey @Naros, can you check out and merge this one if you don't see any issues? Intention is to get rid the inline CSS (margin etc.) around images. I checked a few pages and it looked good.
All the styling is in CSS now, so that's better. To give some context: the raw HTML is done to assign the "responsive-image" class to images. Ideally that all shouldn't be needed to begin with as AsciiDoctor should make images responsive itself, but for whatever reason it doesn't in our case. Unfortunately, there's also no way to give a class for an AsciiDoctor `image`, hence the fall-back to raw HTML. But I think it's acceptable with this fix here.
Note this should be preferred:
```
[.imageblock.centered-image]
====
++++
++++
====
```
Over 
```
++++
<div class="imageblock centered-image">
</div>
++++ …
```
> Removing inline styles from images

- _antora/supplemental_ui/css/debezium-antora.css
- _antora/supplemental_ui/js/jquery.ba-floatingscrollbar.js
- _antora/supplemental_ui/layouts/default.hbs
- _antora/supplemental_ui/partials/article.hbs
- _antora/supplemental_ui/partials/head-styles.hbs
https://issues.redhat.com/browse/DBZ-1668
This PR has a sibling PR in the main repo, https://github.com/debezium/debezium/pull/1216.  We should make sure that the main repo PR is merged prior to this.  
* Reworked Antora UI
* ToC is now flush to right of window
* Documentation content uses responsive layout to maximize render space
* Removed all obsolete responsive CSS for wider screen widths
* Asciidoc changes
* Tables are now stripped and rendered with grid orders
* Table headers now have a darker background color
* Tables rendered using horizontal scrollbar when overflowing
* Rendering of other blocks such as listings and examples to be consistent
* HighlightJS changes
* Improved color rendering for Java and and XML
This PR supersedes …
> DBZ-1668 Documentation rendering enhancements

- README.md
The repository URL seems to be leftover from an older repo.
> Fix repo url in README

- .travis.yml
- Rakefile
- _antora/supplemental_ui/css/debezium-antora.css
https://issues.redhat.com/browse/DBZ-1798
In commit 27645e8, I am forcing the Travis CI build step to generate a `.nojekyll` file in the pre-build steps since Awestruct does not copy the `.nojekyll` file from the root of the repository.  This should allow images stored in `/documentation/reference/_images` to be rendered as they'll be published to github pages where-as previously without the `.nojekyll` they were not.
In commit 22248d2, this should resolve the overflow issue when browser window size is smaller than 1600px, forcing the image to respect aspect ratio and resize appropriately based on resolution.
> DBZ-1798 Fix miscellaneous documentation issues

- CONTRIBUTING.md
- _data/releases/0.10/series.yml
- _data/releases/0.9/series.yml
- _data/releases/1.0/series.yml
- _data/releases/1.1/series.yml
- _data/releases/1.2/series.yml
- _layouts/releases.html.haml
- releases/index.html.haml
- stylesheets/debezium.less
https://issues.redhat.com/browse/DBZ-2031
This PR modifies the `series.yml` definition so that both database and driver version metadata can be placed in the YAML files in `_data/releases/<major>.<minor>/series.yml` files and rendered on the releases overview and specific release page test matrix tables.
> DBZ-2031 Add JDBC driver versions to release metadata

- _antora/supplemental_ui/css/debezium-antora.css
- _antora/supplemental_ui/partials/article.hbs
- _antora/supplemental_ui/partials/banner-current.hbs
- _antora/supplemental_ui/partials/banner-development.hbs
- _antora/supplemental_ui/partials/banner-outdated.hbs
https://issues.redhat.com/browse/DBZ-1951
So I decided to base the logic on when to apply the version banner because I wanted to see if we can do this without introducing even more steps to the release process for maintaining attributes. Antora maintains an array of versions and we use this array to compare against the version of the page rendered to see whether to apply the "development" or "outdated" banners.  
The banner placement is probably not ideal at the moment since it scrolls with the page content but in order to avoid problems with other rendering concerns, we can't make it static above the breadcrumbs portion of the page since the content that is scrollable is offset by a fixed number of pixels.
I'm open to any feedback or suggestions.
> DBZ-1951 Introduce banner for development/older versions

- _antora/supplemental_ui/css/debezium-antora.css
- _antora/supplemental_ui/partials/article.hbs
- _antora/supplemental_ui/partials/banner-current.hbs
- _antora/supplemental_ui/partials/banner-development.hbs
- _antora/supplemental_ui/partials/banner-outdated.hbs
Reverts debezium/debezium.github.io#461
Agh, noticed one issue: It uses 1.2 as the current stable, instead of 1.1. Probably an easy fix.
> Revert "DBZ-1951 Introduce banner for development/older versions"

- CONTRIBUTING.md
- _antora/supplemental_ui/css/debezium-antora.css
- _antora/supplemental_ui/helpers/gt.js
- _antora/supplemental_ui/partials/article.hbs
- _antora/supplemental_ui/partials/banner-current.hbs
- _antora/supplemental_ui/partials/banner-development.hbs
- _antora/supplemental_ui/partials/banner-outdated.hbs
- _antora/supplemental_ui/partials/banner.hbs
- playbook.yml
- playbook_author.yml
https://issues.redhat.com/browse/DBZ-1951
This is the reworked implementation after being reverted in #463.  This should currently specify that version 1.1 is the current version, master/1.2 are the development iterations, and anything prior to version 1.1 is deemed out-dated.
> DBZ-1951 Rework introduction of banner for development/older versions

- playbook.yml
- playbook_author.yml
This PR is needed for https://github.com/debezium/debezium/pull/1886 so that the documentation overrides for the `context` global variable will work properly for newer versions of the documentation but also so that older versions of the documentation are generated as they always have without warnings of a missing `context` variable.
> Enable overriding of the documentation context global variable

- CONTRIBUTING.md
- README.md
updating the readme for the website-migration branch.  Essentially it is now the same as the develop branch with appropriate edits for the jekyll setup.  Will need further updates as additional changes are made to the process
> Update readme for website-migration

- _layouts/post.html
- assets/css/custom.css
- Added the blog navigation option to move to "next" and "previous" posts from the blog page itself.
Screenshot
> Adding button to move to next and previous blog

- _includes/release-version.html
Removes the unnecessary `.Final` text from the SQL Server download link from the releases page.
> Fix SQL Server artifact download link

- _data/releases/1.5/series.yml
https://issues.redhat.com/browse/DBZ-3124
The Vitess gRPC client version 9.0.0 has the additional gRPC field that contains Enum's permitted values.
Related PRs:
- Feature implementation: https://github.com/debezium/debezium-connector-vitess/pull/20
- Vitess Connector documentation: https://github.com/debezium/debezium/pull/2142
> DBZ-3124 Upgrade Vitess gRPC client version to 9.0.0 for Enum support

- ANTORA.md
- README.md
readme updates - attempting to clarify how to build debezium docs using local debezium repo when previewing the website. 
In the main readme, I added a section which is specific to building docs using local debezium repo, since it requires a few differences (getting clone of the repo, adding a volume mapping for debezium repo, and using the 'author' option in the rake command)
In the antora readme, I referred back to the main readme and the importance of adding the volume mapping when building from local repo.
> Readme updates

- community/users.asciidoc
Zalando has been using Debezium successfully for a couple of years now.
> Adding Zalando to Debezium's user list
