.gitignore, Rakefile
- gitignore refresh
- remove non local installs of gems
=> Minor improvements

_config/authors.yml, blog/2016-05-31-Debezium-on-Kubernetes.adoc
A few minor fixes to @christian-posta's post. Closes and supersedes https://github.com/debezium/debezium.github.io/pull/11
=> Add a blog post for running debezium on Kubernetes

blog/2017-02-07-Debezium-0-4-0-Released.adoc, docs/connectors/index.html.haml, docs/connectors/mongodb.asciidoc, docs/connectors/mysql.asciidoc, docs/connectors/postgresql.asciidoc, docs/faq.asciidoc, docs/install.asciidoc, docs/releases.asciidoc, docs/tutorial-for-0-3.asciidoc, docs/tutorial.asciidoc
Changes to the website for the 0.4.0 release. **_This should be merged only after the remaining changes for the 0.4.0 release are incorporated and the release is made._**
=> Release 0.4.0

_config/authors.yml, _layouts/blog-post.html.haml, blog/2016-09-19-Serializing-Debezium-events-with-Avro.adoc, blog/2017-02-22-Debezium-at-WePay.adoc
This was authored by @criccomini and appeared originally on the [WePay Engineering blog](https://wecode.wepay.com/posts/streaming-databases-in-realtime-with-mysql-debezium-kafka), and Chris agreed to cross-post on Debezium.
=> Added WePay blog post

docs/connectors/mysql.asciidoc
Added the documentation for POINT data type per [DBZ-222](https://issues.jboss.org/browse/DBZ-222). 
P/S: Sorry for the formatting issues.
FYI @gunnarmorling
=> DBZ-222 Updated the docs for POINT

docs/connectors/mysql.asciidoc
New section in the MySQL connector documentation.
=> DBZ-293 Added documentation of the MySQL connector’s JMX metrics

docs/connectors/mysql.asciidoc
Can be merged right away, no need to wait for the next release.
=> Fixing several typos in MySQL connector doc

blog/2017-08-17-debezium-0-5-2-is-out.adoc
Hey @rhauch, would you perhaps have a few minutes for a quick review of the 0.5.2 announcement?
=> Adding release announcement for 0.5.2

docs/faq.asciidoc
“enable” is more active and compelling than “let”, IMHO.
=> Docs: language tweak in FAQ

docs/connectors/postgresql.asciidoc, docs/faq.asciidoc
As per this chat: https://gitter.im/debezium/user?at=59a090ee9acddb2407cc16d9
=> Add notes on hosted PostgreSQL such as RDS, Heroku

_config/site.yml
As per this thread: https://github.com/awestruct/awestruct/issues/265#issuecomment-15509028
Spurred by this: https://github.com/debezium/debezium.github.io/pull/61#issuecomment-325661825
=> Set character encoding in Awestruct config

blog/2017-09-21-debezium-0-6-0-released.adoc
=> Adding 0.6 release announcement

blog/2017-10-26-debezium-0-6-1-released.adoc
@rhauch, @jpechane, any thoughts on the announcement blog post?
=> 0.6.1 release announcement

docs/embedded.asciidoc
See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/debezium/2QKU0_qECCI/vB3xH-BbBwAJ for source
=> Fix example code for embedded

_config/site.yml, docs/releases.asciidoc, docs/tutorial-for-0-6.asciidoc
@gunnarmorling Could you please describe breaking changes for DBZ-342. You know much more about this change than I do.
=> 0.7 release documentation

docs/connectors/postgresql.asciidoc
https://issues.jboss.org/browse/DBZ-498
=> DBZ-498 Unknown datatypes handling

docs/connectors/mysql.asciidoc
https://issues.jboss.org/browse/DBZ-461
=> DBZ-461 Changed default bigint conversion to long

docs/connectors/postgresql.asciidoc
https://issues.jboss.org/browse/DBZ-258
=> DBZ-258 Documentation for wal2json plug-in

docs/openshift.asciidoc
updating the Openshift docs
will update the examples repo as well ...
=> Using new Strimzi project resources

_config/site.yml, docs/tutorial.asciidoc, stylesheets/debezium.less
https://issues.jboss.org/browse/DBZ-369
=> DBZ-369 Add TOC and clickable sections to tutorial

docs/faq.asciidoc
https://issues.jboss.org/browse/DBZ-368
=> DBZ-368 Document capacity of default memory settings

docs/openshift.asciidoc
@gunnarmorling I forgot the text updates ;-)
=> Removing last EnMasse mentions

docs/faq.asciidoc
https://issues.jboss.org/browse/DBZ-548
=> DBZ-548 FAQ for DECIMAL decoding from binary representation

docs/connectors/mysql.asciidoc
https://issues.jboss.org/browse/DBZ-541
=> DBZ-541 Filter history for monitored tables only

docs/connectors/postgresql.asciidoc
https://issues.jboss.org/browse/DBZ-590
=> DBZ-590 Document WAL retention

docs/connectors/mysql.asciidoc
https://issues.jboss.org/browse/DBZ-588
=> DBZ-588 Inconsistent schema handling mode

docs/connectors/mysql.asciidoc
https://issues.jboss.org/browse/DBZ-220
=> DBZ-220 Force DBZ to commit regularly

docs/connectors/postgresql.asciidoc
https://issues.jboss.org/browse/DBZ-631
=> DBZ-631 Document varibale scale decimal

docs/connectors/postgresql.asciidoc
https://issues.jboss.org/browse/DBZ-619
=> DBZ-619 Document wal2json on RDS limitations

_layouts/blog-post.html.haml, _layouts/blog.html.haml, _partials/leftcol-blog.html.haml, stylesheets/debezium.less
https://issues.jboss.org/browse/DBZ-574
=> DBZ-574 Panel with 7 latest blogposts

docs/tutorial.asciidoc
Removes an extra dash `(with '--it')` -> `(with '-it')`
=> Remove extra dash in -it command

docs/connectors/mysql.asciidoc
https://issues.jboss.org/browse/DBZ-728
=> DBZ-728 Fix inconsistent names for history consumer/producer options

docs/connectors/mysql.asciidoc
@jpechane Some more doc updates.
https://issues.jboss.org/browse/DBZ-601
=> Misc 0.8 docs for snapshot.delay.ms

docs/connectors/postgresql.asciidoc
add more information about valid names and link to Postgres documentation
https://issues.jboss.org/browse/DBZ-746
=> DBZ-746 add info about valid postgres slot names

docs/connectors/mysql.asciidoc, docs/connectors/postgresql.asciidoc
@jpechane Doc update as per the latest TZ changes
=> DBZ-578 Doc updates around TZ changes

docs/connectors/postgresql.asciidoc
https://issues.jboss.org/browse/DBZ-772
=> DBZ-772 Document streaming mode for wal2json decoder

docs/connectors/mysql.asciidoc, docs/connectors/postgresql.asciidoc
https://issues.jboss.org/browse/DBZ-573
=> DBZ-573 Geometry documentation

docs/faq.asciidoc
https://issues.jboss.org/browse/DBZ-774
=> DBZ-774 FAQ entry for offset manipulation

docs/connectors/postgresql.asciidoc
https://issues.jboss.org/projects/DBZ/issues/DBZ-762
@jpechane, docs for DBZ-762.
=> DBZ-762 Adding CITEXT to list of supported column types

docs/connectors/mysql.asciidoc
Documentation for https://github.com/debezium/debezium/pull/568
=> DBZ-789 Rows scanned snapshot metrics

docs/roadmap.asciidoc
@jpechane Can you check out this update to the roadmap? Thanks!
=> Roadmap update after 0.8 release

docs/connectors/mysql.asciidoc
@jpechane Small fall-out of reviewing https://github.com/debezium/debezium/pull/607.
=> DBZ-866 Updating docs of 'source' block for MySQL connector

docs/online-resources.asciidoc
add link to presentation talk "I need my data and a little bit of your data". - Integrating services with Apache Kafka by René Kerner
=> add link to presentation talk

docs/configuration/event-flattening.asciidoc, docs/configuration/logging.asciidoc, docs/connectors/mongodb.asciidoc, docs/connectors/mysql.asciidoc, docs/connectors/postgresql.asciidoc, docs/connectors/sqlserver.asciidoc
If merged, this PR addresses a number of spelling/grammatical issues I noticed while reading the documentation.
* I did not create a corresponding JIRA issue for these but am happy to do so and rename the feature branch if necessary.
* I separated each file out into a separate commit to make the diff-ing easier to review but am happy to squash into a single one prior to merge if that is preferred.
It's my first contribution to this repository so if I missed anything in the guidelines, please let me know and I'll be happy to address it.
=> Fix spelling/grammatical errors

docs/connectors/mysql.asciidoc
https://issues.jboss.org/browse/DBZ-757
=> DBZ-757 Use antlr parser by default

docs/connectors/mysql.asciidoc
Add a missing comma to the example configuration JSON document
=> Fix minor typo

docs/connectors/sqlserver.asciidoc
https://issues.jboss.org/browse/DBZ-1067
=> DBZ-1067 Adding column.blacklist option to SQL Server docs

blog/2019-01-28-debezium-0-9-0-cr1-released.adoc
@jpechane, can you take a look?
=> Adding 0.9.0.CR1 release announcement

docs/connectors/postgresql.asciidoc
https://issues.jboss.org/browse/DBZ-1146
=> DBZ-1146 Documentation update

blog/2019-02-25-debezium-0-9-2-final-released.adoc
Hey @jpechane, can you review and merge this one? I'll send the Tweet later today. Thanks!
=> Adding Debezium 0.9.2 release announcement

docs/connectors/postgresql.asciidoc
https://issues.jboss.org/browse/DBZ-1130
=> DBZ-1130 Documenting new "slot.stream.params" connector option

docs/connectors/mongodb.asciidoc
Added new property corresponding to the following commit:
https://github.com/debezium/debezium/pull/774
=> DBZ-867 add property snapshot.mode for MongoDB

docs/connectors/postgresql.asciidoc
https://issues.jboss.org/browse/DBZ-1219
=> DBZ-1219 Document RDS Postgres wal_level behavior

docs/connectors/mysql.asciidoc
https://issues.jboss.org/browse/DBZ-1143
=> DBZ-1143 2-digit years conversion option

docs/connectors/postgresql.asciidoc
Updated the Postgres Docs for added support for network address types
=> [DBZ-1193] Updated the Postgres Doc for added column support for network address types.

docs/connectors/sqlserver.asciidoc
Follow-up to https://github.com/debezium/debezium.github.io/pull/293#issuecomment-493893354
=> Document lack of capture access privileges

docs/connectors/mysql.asciidoc
to explicit authorized value of length for column.mask.with.length.chars
=> Update documentation colun.mask.with.length.chars

docs/connectors/mysql.asciidoc
https://issues.jboss.org/browse/DBZ-736
=> DBZ-736 Update documentation on removal of MySQL legacy parser

docs/configuration/outbox-event-router.asciidoc
https://issues.jboss.org/browse/DBZ-1289
@renatomefi, could you take a look? This is one part of it, code PR for some related fixes coming in a bit.
=> DBZ-1289 Outbox router doc fix

docs/connectors/mongodb.asciidoc, docs/connectors/mysql.asciidoc, docs/connectors/postgresql.asciidoc, docs/connectors/sqlserver.asciidoc
@jpechane I've begun with the doc update around the source block changes. I've got two questions, I'll add inline comments for those. I'll push more commits tomorrow for the remaining connectors. Thanks!
=> DBZ-1235 Doc Updates

blog/2019-05-29-debezium-0-10-0-alpha1-released.adoc
=> Adding 0.10.0.Alpha1 release announcement

docs/connectors/mysql.asciidoc, docs/connectors/oracle.asciidoc, docs/connectors/postgresql.asciidoc
@jpechane, can you review + merge? Thanks!
=> DBZ-1283 Clarifying that "database.server.name" is mandatory

blog/2019-06-12-debezium-0-10-0-beta1-released.adoc
@jpechane, @Naros, could one of you review and merge? Thanks!
=> Adding 0.10.0.Beta1 release announcement

docs/faq.asciidoc
https://issues.jboss.org/browse/DBZ-799
=> DBZ-799 Causes for offset flush timeouts

docs/connectors/oracle.asciidoc, docs/connectors/sqlserver.asciidoc
https://issues.jboss.org/browse/DBZ-835
=> DBZ-835 Document optional tombstone

docs/index.html.haml
Please find attached a PR that fixes a dead link to @gunnarmorling 's video talk on the main page of the documentation. A minor wording issue was fixed as well.
=> Minor doc fixes

docs/connectors/mongodb.asciidoc
https://issues.jboss.org/browse/DBZ-1198
=> DBZ-1198 Heartbeat for MongoDB

docs/connectors/mysql.asciidoc, docs/connectors/oracle.asciidoc, docs/connectors/sqlserver.asciidoc
https://issues.jboss.org/browse/DBZ-1120
=> DBZ-1120 Finalize and document JMX metrics

docs/configuration/event-flattening.asciidoc
Documentation update for https://github.com/debezium/debezium/pull/968
=> DBZ-1395 Update event-flattening documentation for adding source fields

docs/connectors/mysql.asciidoc, docs/connectors/oracle.asciidoc, docs/connectors/sqlserver.asciidoc
Apply after https://github.com/debezium/debezium.github.io/pull/321
=> DBZ-1356 Document schema history metrics

docs/embedded.asciidoc
- `server.id` replaced with `database.server.id` 
- minimal Executor instanciation
=> [DBZ-393] Improve embedded documentation

docs/connectors/postgresql.asciidoc
https://issues.jboss.org/browse/DBZ-1035
This depends on https://github.com/debezium/debezium/pull/981
=> DBZ-1035 Document new PostgreSQL Exported Snapshot feature

docs/online-resources.asciidoc
Added link to "SQL Server Change Stream sample using Debezium
=> Added link

docs/configuration/event-flattening.asciidoc
https://issues.jboss.org/browse/DBZ-1448
=> DBZ-1448 Documentation clarification

blog/2019-09-26-debezium-0-10-0-cr2-released.adoc
@Naros, @jpechane, can be merged after the release is done (and addressing any feedback you may have of course). Thanks!
=> 0.10.0.CR2 release announcement

blog/2019-10-02-debezium-0-10-0-final-released.adoc
@jpechane, @Naros, feedback welcome!
=> 0.10.0.Final release announcement

roadmap.asciidoc
@jpechane, could you review + merge? Thanks! / CC @Naros.
=> Roadmap update

blog/2019-10-17-debezium-newsletter-02-2019.adoc
https://issues.jboss.org/browse/DBZ-1547
=> DBZ-1547 02/2019 Newletter

_antora/supplemental_ui/css/debezium-antora.css, _antora/supplemental_ui/partials/page-versions.hbs
https://issues.jboss.org/browse/DBZ-1584
=> DBZ-1584 Fix inconsistent rendering order of versions in drop-down

documentation/faq.asciidoc
=> Trivial grammar fix.

community/users.asciidoc
=> Add Traveloka to Debezium users

community/users.asciidoc
See: https://github.com/debezium/debezium/pull/1148
=> Add Segment to users page

community/users.asciidoc
=> Fix Segment/Ctlstore link

documentation/online-resources.asciidoc
@gunnarmorling I've added a couple more links to blog articles I've written, is that OK?
=> Add links to some of my Debezium blogs

_antora/supplemental_ui/css/debezium-antora.css
https://issues.redhat.com/browse/DBZ-1652
This issue depends on the documentation changes in https://github.com/debezium/debezium/pull/1162
=> DBZ-1652 Added CSS code-wordbreak styles for table rendering

community/users.asciidoc
=> Add Experience to Debezium users

playbook.yml, playbook_author.yml
https://issues.redhat.com/browse/DBZ-1687
This PR depends on https://github.com/debezium/debezium/pull/1224 [master] and https://github.com/debezium/debezium/pull/1225 [1.1]
=> DBZ-1687 Consolidate attributes

community/users.asciidoc
Lendingkart is one of user of Debizium
=> Lendingkart Debizium

documentation/faq.asciidoc
https://issues.redhat.com/browse/DBZ-1694
=> DBZ-1694 Document column swap

roadmap.asciidoc
@jpechane, @Naros, @jcechace, here's a basic roadmap update. Feedback for additions/changes/removals welcome!
=> 🛣️ Updating roadmap

blog/2020-03-19-integration-testing-for-change-data-capture-with-testcontainers.adoc
Hey @Naros, would you mind taking a quick look at this one and let me know about any comments you may have? Thx!
=> Testcontainers blog post

roadmap.asciidoc
With release of 1.1.0.Final, remove those items from the roadmap.
=> Remove 1.1 items from roadmap

_antora/supplemental_ui/css/debezium-antora.css
https://issues.redhat.com/browse/DBZ-1920
* Fixes right-nav bar wrapping
* Add underline for sections at levels 3 and 4
=> DBZ-1920 Various CSS fixes

_data/releases/0.9/series.yml, _layouts/releases.html.haml
https://issues.redhat.com/browse/DBZ-1979
=> DBZ-1979 - Version selector should show all releases

community/users.asciidoc
Hey @bibryam, is this what you had in mind? Aware of any others?
=> Adding Integrations section to users page

roadmap.asciidoc
@jpechane, @Naros, @bibryam, feedback welcome on this community roadmap update for 1.3. Proably also a good idea to talk about it in next Monday's call.
=> 🗺️ Roadmap update

community/users.asciidoc
For some reason it doesn't pic
=> Added IBM Event Streams integration

Rakefile, _ext/featured_posts.rb
https://issues.redhat.com/browse/DBZ-2374
=> DBZ-2374 Fix featured blog post script & CI exit code propagation.

blog/2020-09-16-debezium-1-3-beta2-released.adoc
@Naros, feedback and improvements welcome! Please merge at your discretion. Thx!
=> Adding 1.3 Beta2 release announcement

community/users.asciidoc
=> Add GoHealth to Debezium users

blog/2020-10-22-towards-debzium-ui.adoc
@rk3rn3r, @bibryam, feedback welcome!
=> Announcing Debezium UI PoC

_config.yml, _includes/blog-feed.html, _layouts/blog.html, _layouts/tag.html, blog/index.html, tag/index.html
=> Fixed blog pagination issue

_posts/2018-08-30-streaming-mysql-data-changes-into-kinesis.adoc, _posts/2018-09-20-materializing-aggregate-views-with-hibernate-and-debezium.adoc, _posts/2018-12-05-automating-cache-invalidation-with-change-data-capture.adoc, _posts/2018-12-19-debezium-0-9-0-beta2-released.adoc, _posts/2019-02-05-debezium-0-9-0-final-released.adoc, _posts/2019-02-13-debezium-0-9-1-final-released.adoc, _posts/2019-02-19-reliable-microservices-data-exchange-with-the-outbox-pattern.adoc, _posts/2019-03-14-debezium-meets-quarkus.adoc, _posts/2019-05-23-tutorial-using-debezium-connectors-with-apache-pulsar.adoc, _posts/2019-07-08-tutorial-sentry-debezium-container-images.adoc, _posts/2019-07-12-streaming-cassandra-at-wepay-part-1.adoc, _posts/2019-10-01-audit-logs-with-change-data-capture-and-stream-processing.adoc, _posts/2019-10-08-handling-unchanged-postgres-toast-values.adoc, _posts/2019-10-22-audit-logs-with-kogito.adoc, _posts/2019-12-18-debezium-1-0-0-final-released.adoc, _posts/2020-02-10-event-sourcing-vs-cdc.adoc, _posts/2020-02-19-debezium-camel-integration.adoc, _posts/2020-02-25-lessons-learned-running-debezium-with-postgresql-on-rds.adoc, _posts/2020-03-05-db2-cdc-approaches.adoc, _posts/2020-03-31-debezium-newsletter-01-2020.adoc, _posts/2020-09-15-debezium-auto-create-topics.adoc, _posts/2020-10-08-debezium-community-stories-with-renato-mefi.adoc
- Updated the images asset path in the blog content.
=> updated the images path in the blog content

_config.yml, _includes/release-version.html, _includes/release.html, _layouts/release-version.html
Additional work towards making the release pages data driven
=> data drive release pages

_includes/breadcrumb.html, _includes/documentation.html, _posts/2019-05-06-debezium-0-9-5-final-released.adoc, _posts/2019-05-29-debezium-0-10-0-alpha1-released.adoc, community.md, index.md
- Updated documentation landing page(data driven).
- Added the title for the home and community page.
- Fixed the version dropdown in release breadcrumb.
=> Updated data driven documentation landing page and minor Fixes

_data/releases/1.4/1.4.0.Alpha1.yml, community/code-of-conduct.asciidoc, community/contribute.asciidoc, community/users.asciidoc, documentation/faq.asciidoc, documentation/online-resources.asciidoc, license.asciidoc, releases/0.1/release-notes.asciidoc, releases/0.10/release-notes.asciidoc, releases/0.2/release-notes.asciidoc, releases/0.3/release-notes.asciidoc, releases/0.4/release-notes.asciidoc, releases/0.5/release-notes.asciidoc, releases/0.6/release-notes.asciidoc, releases/0.7/release-notes.asciidoc, releases/0.8/index.asciidoc, releases/0.8/release-notes.asciidoc, releases/0.9/release-notes.asciidoc, releases/1.0/release-notes.asciidoc, releases/1.1/release-notes.asciidoc, releases/1.2/release-notes.asciidoc, releases/1.3/release-notes.asciidoc, releases/1.4/release-notes.asciidoc, roadmap.asciidoc
- removes awestruct attributes from some asciidocs
- fixes incorrect announcement url
=> Website migration doc updates

CONTRIBUTING.md, _data/releases/1.3/1.3.1.Final.yml, _posts/2020-11-12-debezium-1-3-1-final-released.adoc, releases/1.3/release-notes.asciidoc
- Additional updates to 'CONTRIBUTING.md' to adapt to jekyll site
- Adding recent content from develop branch
=> updates to contributing doc, adding recent content

_data/releases/1.4/1.4.0.Alpha2.yml, _data/releases/1.4/versions.yml, _includes/blog-menu.html, releases/1.4/release-notes.asciidoc
- now sorting tags on blog page to agree with current site
- adding recent release content
=> Website migration updates

_data/releases/1.4/1.4.0.Alpha2.yml, _posts/2020-11-17-debezium-1-4-alpha2-released.adoc
adding latest blog post to website-migration branch
=> sync website-migration with latest

_antora/supplemental_ui/partials/header-content.hbs, _includes/banner.html, _includes/topbar.html
- minor update on banner for tutorial link
- fix link for issue #554
=> minor updates for migration

.gitignore, ANTORA.md, CONTRIBUTING.md, README.md
additional doc updates removing awestruct references and updating the docker image reference
=> readme updates for migration website

Gemfile.lock, _includes/banner.html, _includes/project-footer.html, assets/css/custom.css
Fixed scrollbar issues on mobile view
Fixed banner padding issue
=> Fixing responsive issues

playbook.yml, playbook_author.yml
applying the change from the referenced PR.  @uidoyen It looks like we may have missed this change in website-migration branch - can you confirm?  https://github.com/debezium/debezium.github.io/pull/504
=> apply PR504 for website-migration

Gemfile, _config.yml, _includes/blog-menu.html, _layouts/archive.html, archive.md
- Adding the archive option in the blog-menu.
Screenshot
=> Latest archive

_data/connectors.yml, _data/releases/0.1/series.yml, _data/releases/0.10/series.yml, _data/releases/0.2/series.yml, _data/releases/0.3/series.yml, _data/releases/0.4/series.yml, _data/releases/0.5/series.yml, _data/releases/0.6/series.yml, _data/releases/0.7/series.yml, _data/releases/0.8/series.yml, _data/releases/0.9/series.yml, _data/releases/1.0/series.yml, _data/releases/1.1/series.yml, _data/releases/1.2/series.yml, _data/releases/1.3/series.yml, _data/releases/1.4/series.yml, _includes/release-version.html
Added Vitess Connector plug-in and updated `series.yml` to make download connector plug-in drop-down data-driven.
=> DBZ-2907 Adding Vitess Connector

_data/releases/1.5/series.yml, _includes/release.html
https://issues.redhat.com/browse/DBZ-3100
Related PRs:
- Vitess Connector Documentation: https://github.com/debezium/debezium/pull/2121
- Vitess tutorial: https://github.com/debezium/debezium-examples/pull/156
=> DBZ-3100 Vitess Connector supports Vitess 9.0.0

_data/releases/1.5/series.yml
https://issues.redhat.com/browse/DBZ-3215
=> DBZ-3215 Update Oracle versions tested with Debezium 1.5

_data/releases/1.5/1.5.0.Beta2.yml, _posts/2021-03-15-debezium-1-5-beta2-released.adoc
@gunnarmorling @jpechane Could you please review and let me know if any changes are needed?  I'll merge this in 2 hours at, 4:30pm UTC.
=> 1.5.0.Beta2 announcement

.github/workflows/gh-pages-deployment.yml, .github/workflows/gh-pages-staging-deployment.yml
https://issues.redhat.com/browse/DBZ-3320
In reference with https://github.com/debezium/debezium/pull/2250
=> DBZ-3320 Trigger workflows on docs update

documentation/faq.asciidoc
https://issues.redhat.com/browse/DBZ-3355
=> DBZ-3355 Document configuration of max.request.size

README.md
https://issues.redhat.com/browse/DBZ-3383
=> DBZ-3383 Fix wrong badge in README

_data/releases/1.6/series.yml
https://issues.redhat.com/browse/DBZ-3460
=> DBZ-3460 Add Oracle driver 21.1.0.0 compatibility

_data/releases/1.6/1.6.0.Beta2.yml, _posts/2021-06-10-debezium-1-6-beta2-released.adoc
@Naros, native speaker validation welcomed :)
=> 1.6.0.Beta2 release announcement

_includes/release.html
=> Truncate the release summary to 120 char.

community/users.asciidoc
Added DeviantArt as Debezium user.
=> Added DeviantArt as Debezium user.

_posts/2021-08-02-debezium-1-7-alpha1-released.adoc
@gunnarmorling @Naros This is a skeleton of announcement for Monday publication.
=> Announcement for 1.7.0.Alpha1

_posts/2021-08-31-going-zookeeperless-with-debezium-container-image-for-apache-kafka.adoc
@rk3rn3r, @Naros, up for a quick review of this one? Thx!
=> Adding blog post about using the container image with KRaft mode

.github/workflows/surge_preview.yml, .github/workflows/surge_preview_teardown.yml, CONTRIBUTING.md, README.md
tested PR on staging https://github.com/debezium/debezium.github.io/pull/716
=> DBZ-4011 Add GitHub actions to preview website via surge.sh

.github/workflows/surge-preview.yml, .github/workflows/surge_preview_teardown.yml
Pending surge.sh preview teardown action https://issues.redhat.com/browse/DBZ-4011
=> DBZ-4011 Surge preview teardown
